begin;

alter table public.clientes
  add column frecuencia_compra_dias integer,
  add column dias_entrega integer[] not null default '{}',
  add column proxima_entrega date,
  add column activo boolean not null default true,
  add constraint clientes_frecuencia_compra_dias_check
    check (frecuencia_compra_dias is null or frecuencia_compra_dias > 0),
  add constraint clientes_dias_entrega_check
    check (dias_entrega <@ array[0, 1, 2, 3, 4, 5, 6]);

create table public.planes_cliente_producto (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  id_cliente bigint not null references public.clientes(id),
  id_producto bigint not null references public.productos(id),
  cantidad numeric(14, 4) not null check (cantidad > 0),
  activo boolean not null default true,
  notas text
);

create table public.usuarios_app (
  id_usuario uuid primary key references auth.users(id) on delete cascade,
  rol text not null default 'operador' check (rol in ('administrador', 'operador')),
  activo boolean not null default true,
  fecha_registro timestamptz not null default now()
);

insert into public.usuarios_app (id_usuario, rol)
select id, 'administrador'
from auth.users
on conflict (id_usuario) do nothing;

create or replace function public.es_usuario_cookie_compass()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.usuarios_app
    where id_usuario = auth.uid() and activo
  );
$$;

create unique index planes_cliente_producto_activo_unique
  on public.planes_cliente_producto (id_cliente, id_producto)
  where activo;
create index planes_cliente_producto_cliente_idx
  on public.planes_cliente_producto (id_cliente);
create index planes_cliente_producto_producto_idx
  on public.planes_cliente_producto (id_producto);
create table public.materias_primas (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  nombre text not null check (btrim(nombre) <> ''),
  unidad_base text not null check (btrim(unidad_base) <> ''),
  stock_minimo numeric(14, 4) not null default 0 check (stock_minimo >= 0),
  activo boolean not null default true,
  unique (nombre)
);

create table public.recetas (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  id_producto bigint not null references public.productos(id),
  nombre text not null check (btrim(nombre) <> ''),
  rendimiento numeric(14, 4) not null check (rendimiento > 0),
  activo boolean not null default true,
  notas text,
  unique (id, id_producto)
);

create unique index recetas_producto_activo_unique
  on public.recetas (id_producto)
  where activo;
create index recetas_producto_idx on public.recetas (id_producto);

create table public.detalle_recetas (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  id_receta bigint not null references public.recetas(id) on delete cascade,
  id_materia_prima bigint not null references public.materias_primas(id),
  cantidad numeric(14, 4) not null check (cantidad > 0),
  unique (id_receta, id_materia_prima)
);

create index detalle_recetas_materia_prima_idx
  on public.detalle_recetas (id_materia_prima);

create table public.egresos (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  fecha timestamptz not null default now(),
  tipo text not null check (
    tipo in ('compra_materia_prima', 'combustible', 'operacional', 'retiro_personal', 'otro')
  ),
  proveedor text,
  descripcion text,
  total numeric(14, 4) not null check (total >= 0),
  constraint egresos_compra_proveedor_check check (
    tipo <> 'compra_materia_prima'
    or (proveedor is not null and btrim(proveedor) <> '')
  )
);

create index egresos_fecha_idx on public.egresos (fecha);
create index egresos_tipo_idx on public.egresos (tipo);

create table public.detalle_compras (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  id_egreso bigint not null references public.egresos(id) on delete cascade,
  id_materia_prima bigint not null references public.materias_primas(id),
  cantidad numeric(14, 4) not null check (cantidad > 0),
  precio_unitario numeric(14, 4) not null check (precio_unitario >= 0),
  subtotal numeric(14, 4) generated always as (cantidad * precio_unitario) stored,
  unique (id_egreso, id_materia_prima),
  unique (id, id_materia_prima)
);

create index detalle_compras_materia_prima_idx
  on public.detalle_compras (id_materia_prima);

create table public.producciones (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  fecha timestamptz not null default now(),
  id_producto bigint not null references public.productos(id),
  id_receta bigint not null,
  cantidad numeric(14, 4) not null check (cantidad > 0),
  costo_total numeric(14, 4) check (costo_total >= 0),
  observaciones text,
  foreign key (id_receta, id_producto)
    references public.recetas(id, id_producto)
);

create index producciones_producto_idx on public.producciones (id_producto);
create index producciones_receta_idx on public.producciones (id_receta);
create index producciones_fecha_idx on public.producciones (fecha);

create table public.consumos_produccion (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  id_produccion bigint not null references public.producciones(id) on delete cascade,
  id_materia_prima bigint not null references public.materias_primas(id),
  cantidad numeric(14, 4) not null check (cantidad > 0),
  costo_unitario numeric(14, 4) check (costo_unitario >= 0),
  costo_total numeric(14, 4) generated always as (cantidad * costo_unitario) stored,
  unique (id_produccion, id_materia_prima),
  unique (id, id_materia_prima)
);

create index consumos_produccion_materia_prima_idx
  on public.consumos_produccion (id_materia_prima);

create table public.movimientos_inventario (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  fecha timestamptz not null default now(),
  id_materia_prima bigint not null references public.materias_primas(id),
  tipo text not null check (
    tipo in ('compra', 'consumo_produccion', 'ajuste_entrada', 'ajuste_salida')
  ),
  cantidad numeric(14, 4) not null check (cantidad > 0),
  id_detalle_compra bigint,
  id_consumo_produccion bigint,
  comentario text,
  constraint movimientos_inventario_origen_check check (
    (tipo = 'compra' and id_detalle_compra is not null and id_consumo_produccion is null)
    or (tipo = 'consumo_produccion' and id_detalle_compra is null and id_consumo_produccion is not null)
    or (tipo in ('ajuste_entrada', 'ajuste_salida') and id_detalle_compra is null and id_consumo_produccion is null)
  ),
  unique (id_detalle_compra),
  unique (id_consumo_produccion),
  foreign key (id_detalle_compra, id_materia_prima)
    references public.detalle_compras(id, id_materia_prima),
  foreign key (id_consumo_produccion, id_materia_prima)
    references public.consumos_produccion(id, id_materia_prima)
);

create index movimientos_inventario_materia_fecha_idx
  on public.movimientos_inventario (id_materia_prima, fecha);
create index movimientos_inventario_tipo_idx
  on public.movimientos_inventario (tipo);

create or replace function public.establecer_actualizado_en()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

create trigger planes_cliente_producto_actualizado_en
before update on public.planes_cliente_producto
for each row execute function public.establecer_actualizado_en();

create trigger materias_primas_actualizado_en
before update on public.materias_primas
for each row execute function public.establecer_actualizado_en();

create trigger recetas_actualizado_en
before update on public.recetas
for each row execute function public.establecer_actualizado_en();

create view public.stock_materias_primas
with (security_invoker = true)
as
select
  mp.id,
  mp.nombre,
  mp.unidad_base,
  mp.stock_minimo,
  coalesce(
    sum(
      case
        when mi.tipo in ('compra', 'ajuste_entrada') then mi.cantidad
        else -mi.cantidad
      end
    ),
    0
  )::numeric(14, 4) as stock_actual,
  coalesce(
    sum(
      case
        when mi.tipo in ('compra', 'ajuste_entrada') then mi.cantidad
        else -mi.cantidad
      end
    ),
    0
  ) < mp.stock_minimo as bajo_minimo
from public.materias_primas mp
left join public.movimientos_inventario mi on mi.id_materia_prima = mp.id
group by mp.id, mp.nombre, mp.unidad_base, mp.stock_minimo;

create view public.costos_productos
with (security_invoker = true)
as
with costos_materias as (
  select
    dc.id_materia_prima,
    sum(dc.subtotal) / nullif(sum(dc.cantidad), 0) as costo_unitario_promedio
  from public.detalle_compras dc
  group by dc.id_materia_prima
), costos_recetas as (
  select
    r.id as id_receta,
    r.id_producto,
    r.rendimiento,
    count(*) filter (where cm.costo_unitario_promedio is null) as materias_sin_costo,
    sum(dr.cantidad * cm.costo_unitario_promedio) as costo_receta
  from public.recetas r
  join public.detalle_recetas dr on dr.id_receta = r.id
  left join costos_materias cm on cm.id_materia_prima = dr.id_materia_prima
  where r.activo
  group by r.id, r.id_producto, r.rendimiento
)
select
  p.id as id_producto,
  p.nombre as producto,
  cr.id_receta,
  cr.rendimiento,
  cr.materias_sin_costo,
  case when cr.materias_sin_costo = 0 then cr.costo_receta end as costo_receta,
  case
    when cr.materias_sin_costo = 0 then cr.costo_receta / cr.rendimiento
  end as costo_unitario
from public.productos p
join costos_recetas cr on cr.id_producto = p.id;

create or replace function public.registrar_compra_materia_prima(
  p_proveedor text,
  p_detalles jsonb,
  p_fecha timestamptz default now(),
  p_descripcion text default null
)
returns bigint
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_egreso_id bigint;
  v_detalle_id bigint;
  v_item record;
  v_total numeric(14, 4) := 0;
begin
  if p_proveedor is null or btrim(p_proveedor) = '' then
    raise exception using errcode = '22023', message = 'Supplier is required';
  end if;

  if p_detalles is null
     or jsonb_typeof(p_detalles) <> 'array'
     or jsonb_array_length(p_detalles) = 0 then
    raise exception using errcode = '22023', message = 'Purchase details must be a non-empty array';
  end if;

  if (
    select count(*) <> count(distinct x.id_materia_prima)
    from jsonb_to_recordset(p_detalles) as x(
      id_materia_prima bigint,
      cantidad numeric,
      precio_unitario numeric
    )
  ) then
    raise exception using errcode = '22023', message = 'A material may appear only once per purchase';
  end if;

  for v_item in
    select x.id_materia_prima, x.cantidad, x.precio_unitario
    from jsonb_to_recordset(p_detalles) as x(
      id_materia_prima bigint,
      cantidad numeric,
      precio_unitario numeric
    )
    order by x.id_materia_prima
  loop
    if v_item.id_materia_prima is null
       or v_item.cantidad is null
       or v_item.cantidad <= 0
       or v_item.precio_unitario is null
       or v_item.precio_unitario < 0 then
      raise exception using errcode = '22023', message = 'Every purchase detail requires a material, positive quantity, and non-negative unit price';
    end if;

    perform 1
    from public.materias_primas
    where id = v_item.id_materia_prima and activo
    for update;

    if not found then
      raise exception using errcode = '23503', message = 'Purchase references an unknown or inactive material';
    end if;

    v_total := v_total + (v_item.cantidad * v_item.precio_unitario);
  end loop;

  insert into public.egresos (fecha, tipo, proveedor, descripcion, total)
  values (
    coalesce(p_fecha, now()),
    'compra_materia_prima',
    btrim(p_proveedor),
    p_descripcion,
    v_total
  )
  returning id into v_egreso_id;

  for v_item in
    select x.id_materia_prima, x.cantidad, x.precio_unitario
    from jsonb_to_recordset(p_detalles) as x(
      id_materia_prima bigint,
      cantidad numeric,
      precio_unitario numeric
    )
    order by x.id_materia_prima
  loop
    insert into public.detalle_compras (
      id_egreso,
      id_materia_prima,
      cantidad,
      precio_unitario
    )
    values (
      v_egreso_id,
      v_item.id_materia_prima,
      v_item.cantidad,
      v_item.precio_unitario
    )
    returning id into v_detalle_id;

    insert into public.movimientos_inventario (
      fecha,
      id_materia_prima,
      tipo,
      cantidad,
      id_detalle_compra
    )
    values (
      coalesce(p_fecha, now()),
      v_item.id_materia_prima,
      'compra',
      v_item.cantidad,
      v_detalle_id
    );
  end loop;

  return v_egreso_id;
end;
$$;

create or replace function public.registrar_venta(
  p_id_cliente bigint,
  p_detalles jsonb,
  p_fecha timestamptz default now()
)
returns bigint
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_orden_id bigint;
  v_item record;
  v_precio numeric;
  v_total numeric(14, 4) := 0;
begin
  if p_id_cliente is null or not exists (
    select 1 from public.clientes where id = p_id_cliente and activo
  ) then
    raise exception using errcode = '23503', message = 'Customer is unknown or inactive';
  end if;

  if p_detalles is null
     or jsonb_typeof(p_detalles) <> 'array'
     or jsonb_array_length(p_detalles) = 0 then
    raise exception using errcode = '22023', message = 'Sale details must be a non-empty array';
  end if;

  for v_item in
    select x.id_producto, x.cantidad
    from jsonb_to_recordset(p_detalles) as x(id_producto bigint, cantidad numeric)
    order by x.id_producto
  loop
    if v_item.id_producto is null or v_item.cantidad is null or v_item.cantidad <= 0 then
      raise exception using errcode = '22023', message = 'Every sale detail requires a product and positive quantity';
    end if;

    select precio into v_precio
    from public.productos
    where id = v_item.id_producto
    for share;

    if not found then
      raise exception using errcode = '23503', message = 'Sale references an unknown product';
    end if;

    v_total := v_total + (v_item.cantidad * v_precio);
  end loop;

  insert into public.ordenes (fecha_registro, total, id_cliente)
  values (coalesce(p_fecha, now()), v_total, p_id_cliente)
  returning id into v_orden_id;

  insert into public.detalle_ordenes (
    fecha_registro,
    id_orden,
    id_producto,
    cantidad,
    precio_unitario
  )
  select
    coalesce(p_fecha, now()),
    v_orden_id,
    x.id_producto,
    x.cantidad,
    p.precio
  from jsonb_to_recordset(p_detalles) as x(id_producto bigint, cantidad numeric)
  join public.productos p on p.id = x.id_producto;

  update public.clientes
  set proxima_entrega = null
  where id = p_id_cliente
    and proxima_entrega <= coalesce(p_fecha, now())::date;

  return v_orden_id;
end;
$$;

create or replace function public.registrar_produccion(
  p_id_producto bigint,
  p_cantidad numeric,
  p_fecha timestamptz default now(),
  p_observaciones text default null
)
returns bigint
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_receta public.recetas%rowtype;
  v_material record;
  v_produccion_id bigint;
  v_consumo_id bigint;
  v_stock numeric;
  v_costo_unitario numeric;
  v_costo_total numeric(14, 4) := 0;
  v_costo_completo boolean := true;
begin
  if p_id_producto is null or p_cantidad is null or p_cantidad <= 0 then
    raise exception using errcode = '22023', message = 'Product and positive production quantity are required';
  end if;

  select r.* into v_receta
  from public.recetas r
  where r.id_producto = p_id_producto and r.activo;

  if not found then
    raise exception using errcode = 'P0002', message = 'The product has no active recipe';
  end if;

  if not exists (
    select 1 from public.detalle_recetas where id_receta = v_receta.id
  ) then
    raise exception using errcode = '22023', message = 'The active recipe has no materials';
  end if;

  for v_material in
    select
      dr.id_materia_prima,
      (dr.cantidad * p_cantidad / v_receta.rendimiento) as cantidad_requerida
    from public.detalle_recetas dr
    where dr.id_receta = v_receta.id
    order by dr.id_materia_prima
  loop
    perform 1
    from public.materias_primas
    where id = v_material.id_materia_prima and activo
    for update;

    if not found then
      raise exception using errcode = '23503', message = 'Recipe references an unknown or inactive material';
    end if;

    select coalesce(sum(
      case
        when mi.tipo in ('compra', 'ajuste_entrada') then mi.cantidad
        else -mi.cantidad
      end
    ), 0)
    into v_stock
    from public.movimientos_inventario mi
    where mi.id_materia_prima = v_material.id_materia_prima;

    if v_stock < v_material.cantidad_requerida then
      raise exception using
        errcode = '23514',
        message = format(
          'Insufficient stock for material %s: available %s, required %s',
          v_material.id_materia_prima,
          v_stock,
          v_material.cantidad_requerida
        );
    end if;

    select sum(dc.subtotal) / nullif(sum(dc.cantidad), 0)
    into v_costo_unitario
    from public.detalle_compras dc
    where dc.id_materia_prima = v_material.id_materia_prima;

    if v_costo_unitario is null then
      v_costo_completo := false;
    else
      v_costo_total := v_costo_total
        + (v_material.cantidad_requerida * v_costo_unitario);
    end if;
  end loop;

  insert into public.producciones (
    fecha,
    id_producto,
    id_receta,
    cantidad,
    costo_total,
    observaciones
  )
  values (
    coalesce(p_fecha, now()),
    p_id_producto,
    v_receta.id,
    p_cantidad,
    case when v_costo_completo then v_costo_total end,
    p_observaciones
  )
  returning id into v_produccion_id;

  for v_material in
    select
      dr.id_materia_prima,
      (dr.cantidad * p_cantidad / v_receta.rendimiento) as cantidad_requerida
    from public.detalle_recetas dr
    where dr.id_receta = v_receta.id
    order by dr.id_materia_prima
  loop
    select sum(dc.subtotal) / nullif(sum(dc.cantidad), 0)
    into v_costo_unitario
    from public.detalle_compras dc
    where dc.id_materia_prima = v_material.id_materia_prima;

    insert into public.consumos_produccion (
      id_produccion,
      id_materia_prima,
      cantidad,
      costo_unitario
    )
    values (
      v_produccion_id,
      v_material.id_materia_prima,
      v_material.cantidad_requerida,
      v_costo_unitario
    )
    returning id into v_consumo_id;

    insert into public.movimientos_inventario (
      fecha,
      id_materia_prima,
      tipo,
      cantidad,
      id_consumo_produccion
    )
    values (
      coalesce(p_fecha, now()),
      v_material.id_materia_prima,
      'consumo_produccion',
      v_material.cantidad_requerida,
      v_consumo_id
    );
  end loop;

  return v_produccion_id;
end;
$$;

create or replace function public.guardar_receta(
  p_id_producto bigint,
  p_rendimiento numeric,
  p_detalles jsonb,
  p_nombre text default null,
  p_notas text default null
)
returns bigint
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_receta_id bigint;
begin
  if p_id_producto is null or p_rendimiento is null or p_rendimiento <= 0 then
    raise exception using errcode = '22023', message = 'Product and positive yield are required';
  end if;
  if p_detalles is null or jsonb_typeof(p_detalles) <> 'array' or jsonb_array_length(p_detalles) = 0 then
    raise exception using errcode = '22023', message = 'Recipe details must be a non-empty array';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(p_detalles) as x(id_materia_prima bigint, cantidad numeric)
    where x.id_materia_prima is null or x.cantidad is null or x.cantidad <= 0
  ) then
    raise exception using errcode = '22023', message = 'Every recipe detail requires a material and positive quantity';
  end if;

  perform 1 from public.productos where id = p_id_producto for share;
  if not found then
    raise exception using errcode = '23503', message = 'Recipe references an unknown product';
  end if;

  update public.recetas set activo = false
  where id_producto = p_id_producto and activo;

  insert into public.recetas (id_producto, nombre, rendimiento, notas)
  values (
    p_id_producto,
    coalesce(nullif(btrim(p_nombre), ''), 'Receta vigente'),
    p_rendimiento,
    p_notas
  )
  returning id into v_receta_id;

  insert into public.detalle_recetas (id_receta, id_materia_prima, cantidad)
  select v_receta_id, x.id_materia_prima, x.cantidad
  from jsonb_to_recordset(p_detalles) as x(id_materia_prima bigint, cantidad numeric)
  join public.materias_primas mp on mp.id = x.id_materia_prima and mp.activo;

  if (select count(*) from public.detalle_recetas where id_receta = v_receta_id)
     <> jsonb_array_length(p_detalles) then
    raise exception using errcode = '23503', message = 'Recipe references an unknown or inactive material';
  end if;

  return v_receta_id;
end;
$$;

comment on view public.stock_materias_primas is
  'Current material stock derived from inventory movements.';
comment on view public.costos_productos is
  'Estimated active-recipe costs based on weighted average material purchase prices.';

do $$
declare
  v_table text;
  v_policy record;
begin
  foreach v_table in array array[
    'clientes', 'productos', 'ordenes', 'detalle_ordenes',
    'planes_cliente_producto', 'materias_primas', 'recetas', 'detalle_recetas',
    'egresos', 'detalle_compras', 'producciones', 'consumos_produccion',
    'movimientos_inventario'
  ]
  loop
    execute format('alter table public.%I enable row level security', v_table);
    for v_policy in
      select policyname
      from pg_policies
      where schemaname = 'public' and tablename = v_table
    loop
      execute format('drop policy %I on public.%I', v_policy.policyname, v_table);
    end loop;
    execute format(
      'create policy cookie_compass_authenticated_access on public.%I for all to authenticated using (public.es_usuario_cookie_compass()) with check (public.es_usuario_cookie_compass())',
      v_table
    );
  end loop;
end;
$$;

alter table public.usuarios_app enable row level security;
create policy usuarios_app_lectura_propia
  on public.usuarios_app
  for select
  to authenticated
  using (id_usuario = auth.uid());

revoke all on table
  public.clientes, public.productos, public.ordenes, public.detalle_ordenes,
  public.planes_cliente_producto, public.materias_primas, public.recetas,
  public.detalle_recetas, public.egresos, public.detalle_compras,
  public.producciones, public.consumos_produccion, public.movimientos_inventario
from anon;

grant select, insert, update, delete on table
  public.clientes, public.productos, public.ordenes, public.detalle_ordenes,
  public.planes_cliente_producto, public.materias_primas, public.recetas,
  public.detalle_recetas, public.egresos, public.detalle_compras,
  public.producciones, public.consumos_produccion, public.movimientos_inventario
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

revoke all on public.usuarios_app from anon, authenticated;
grant select on public.usuarios_app to authenticated;

revoke all on public.stock_materias_primas, public.costos_productos from anon;
grant select on public.stock_materias_primas, public.costos_productos to authenticated;

revoke execute on function public.es_usuario_cookie_compass() from public, anon;
grant execute on function public.es_usuario_cookie_compass() to authenticated;

revoke execute on function public.registrar_venta(bigint, jsonb, timestamptz) from public, anon;
revoke execute on function public.registrar_compra_materia_prima(text, jsonb, timestamptz, text) from public, anon;
revoke execute on function public.registrar_produccion(bigint, numeric, timestamptz, text) from public, anon;
revoke execute on function public.guardar_receta(bigint, numeric, jsonb, text, text) from public, anon;
grant execute on function public.registrar_venta(bigint, jsonb, timestamptz) to authenticated;
grant execute on function public.registrar_compra_materia_prima(text, jsonb, timestamptz, text) to authenticated;
grant execute on function public.registrar_produccion(bigint, numeric, timestamptz, text) to authenticated;
grant execute on function public.guardar_receta(bigint, numeric, jsonb, text, text) to authenticated;

commit;
